FROM node:18-alpine AS build

RUN apk --no-cache add ca-certificates

WORKDIR /app/covid-globe-server

ENV PATH /app/covid-globe-server/node_modules/.bin:$PATH

COPY package.json ./

COPY yarn.lock ./

RUN yarn install

COPY . ./

RUN yarn run ci


EXPOSE 7001
CMD [ "yarn", "start" ]
